language: python
python:
 - "3.6"

branches:
  only:
  - master

before_install: 
  - openssl aes-256-cbc -K $encrypted_2ab7689927dd_key -iv 
    $encrypted_2ab7689927dd_iv -in id_rsa.tar.gz.enc 
    -out id_rsa.tar.gz -d
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - tar xf ~/id_rsa.tar.gz -C ~
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  

install:
  - pip install yq

script:
  - "/bin/bash helm-sync.sh"

